---
- name: Obsidian - Install
  community.general.flatpak:
    name: md.obsidian.Obsidian
    state: present
    method: user

- name: Proton Email
  block:
    - name: Proton Email - Check if installed
      shell: dpkg -s proton-mail
      register: proton_exists
      ignore_errors: true

    - name: Proton Email - Install
      when: proton_exists is failed
      become: true
      become_user: root
      ansible.builtin.apt:
        deb: https://proton.me/download/mail/linux/ProtonMail-desktop-beta.deb

- name: Postman
  become: true
  become_user: root
  block:
  - name: Postman
    ansible.builtin.get_url:
      url: https://dl.pstmn.io/download/latest/linux_64
      dest: . 

  - name: Postman - Remove existing installation
    ansible.builtin.file:
      path: /opt/postman
      state: absent

  - name: Postman - Unzip new installation
    ansible.builtin.unarchive:
      src: postman-linux-x64.tar.gz
      dest: /opt

  - name: Postman - Remove download
    ansible.builtin.file:
      path: postman-linux-x64.tar.gz
      state: absent
