---
- name: Ensure policies directory exists
  file:
    path: /etc/firefox/policies
    recurse: true
    state: directory

- name: Copy Firefox policies
  copy:
    src: policies.json
    dest: /etc/firefox/policies
