---
- hosts: localhost
  vars:
    local_user: "{{ local_user }}"
  vars_files:
    - group_vars/all
  collections:
    - community.general.flatpak

  become: yes
  become_user: "{{ local_user }}"

  roles:
    - { role: package-managers }
    - { role: base }
    - { role: browsers }
    - { role: cli-tools }
    - { role: dotfiles }
    - { role: games }
    - { role: editors }
    - { role: productivity }
    - { role: runtimes }
    - { role: social }
    - { role: system }
    - { role: terminals }
