---
- name: Go - Install
  block:
  - name: Go - Download
    ansible.builtin.get_url:
      url: https://go.dev/dl/go1.22.3.linux-amd64.tar.gz
      dest: .

  - name: Go - Remove existing installation
    become: true
    become_user: root
    ansible.builtin.file:
      path: /usr/local/go
      state: absent

  - name: Go - Install
    become: true
    become_user: root
    ansible.builtin.unarchive:
      src: go1.22.3.linux-amd64.tar.gz
      dest: /usr/local

  - name: Go - Remove download
    ansible.builtin.file:
      path: go1.22.3.linux-amd64.tar.gz
      state: absent

  - name: Go - Install godoc
    ansible.builtin.command:
      cmd: go install golang.org/x/tools/cmd/godoc@latest

- name: Node - Install
  block:
  - name: NVM - Install
    become: false
    ansible.builtin.shell: >
      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
    args:
      executable: /bin/bash
      chdir: "$HOME"
      creates: "$HOME/.nvm/nvm.sh"

  - name: Node - Install LTS
    become: false
    ansible.builtin.shell: |
      . {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install --lts
    args:
      executable: /bin/bash
      chdir: "{{ ansible_env.HOME }}"

- name: Rust - Install
  block:
  - name: Cargo - Check if installed
    shell: command -v cargo
    register: cargo_exists
    ignore_errors: true

  - name: Rust - Download installer
    when: cargo_exists is failed
    ansible.builtin.get_url:
      url: https://sh.rustup.rs
      dest: /tmp/sh.rustup.rs
      mode: '0755'
      force: 'yes'

  - name: Rust - Install
    when: cargo_exists is failed
    shell: /tmp/sh.rustup.rs -y

- name: Python - Install
  block:
  - name: Pyenv - Install
    ansible.builtin.git:
      repo: https://github.com/pyenv/pyenv.git
      dest: ~/.pyenv

  - name: Pyenv - Install Python Version
    ansible.builtin.command:
      cmd: ~/.pyenv/bin/pyenv install {{ python.version }} --skip-existing

  - name: Pyenv - Set Global Version
    ansible.builtin.command:
      cmd: ~/.pyenv/bin/pyenv global {{ python.version }}
