---
- name: Go - Download
  ansible.builtin.get_url:
    url: https://go.dev/dl/go1.22.3.linux-amd64.tar.gz
    dest: .

- name: Go - Remove existing installation
  become: yes
  become_user: root
  ansible.builtin.file:
    path: /usr/local/go
    state: absent

- name: Go - Install
  become: yes
  become_user: root
  ansible.builtin.unarchive:
    src: go1.22.3.linux-amd64.tar.gz
    dest: /usr/local

- name: Go - Remove download
  ansible.builtin.file:
    path: go1.22.3.linux-amd64.tar.gz
    state: absent

- name: Node - Install
  block:
  - name: NVM - Install
    become: no
    ansible.builtin.shell: >
      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
    args:
      executable: /bin/bash
      chdir: "$HOME"
      creates: "$HOME/.nvm/nvm.sh"

  - name: Node - Install LTS
    become: no
    ansible.builtin.shell: |
      . {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install --lts
    args:
      executable: /bin/bash
      chdir: "{{ ansible_env.HOME }}"
