---
- name: Dotfiles - Get Repo
  ansible.builtin.git:
    repo: "{{ dotfiles.repo }}"
    dest: "{{ dotfiles.path }}"

- name: Dotfiles - Install
  ansible.builtin.command: 
  args:
    cmd: "{{ dotfiles.cmd }}"
    chdir: "{{ dotfiles.path }}"
