---
- name: Keyboard File Copy
  become: true
  become_user: root
  copy:
    src: keyboard
    dest: /etc/default

- name: NerdFont - Download Go NerdFont
  ansible.builtin.get_url:
    url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/Go-Mono.zip
    dest: .

- name: NerdFont - Unzip Go NerdFont
  become: true
  become_user: root
  ansible.builtin.unarchive:
    src: Go-Mono.zip
    dest: /usr/local/share/fonts

- name: NerdFont - Remove Download
  ansible.builtin.file:
    path: Go-Mono.zip
    state: absent


- name: Flameshot - Install
  become: true
  become_user: root
  ansible.builtin.package:
    name: flameshot
    state: present
  
- name: Docker - Install
  become: true
  become_user: root
  block:
  - name: Docker - Create Directory
    ansible.builtin.file:
      path: /opt/docker
      state: directory

  - name: Docker - Download Packages
    ansible.builtin.shell: |
      curl -o containerd.io.deb https://download.docker.com/linux/ubuntu/dists/jammy/pool/stable/amd64/containerd.io_1.7.20-1_amd64.deb
      curl -o docker-ce.deb https://download.docker.com/linux/ubuntu/dists/jammy/pool/stable/amd64/docker-ce_27.1.2-1~ubuntu.22.04~jammy_amd64.deb
      curl -o docker-ce-cli.deb https://download.docker.com/linux/ubuntu/dists/jammy/pool/stable/amd64/docker-ce-cli_27.1.2-1~ubuntu.22.04~jammy_amd64.deb
      curl -o docker-buildx-plugin.deb https://download.docker.com/linux/ubuntu/dists/jammy/pool/stable/amd64/docker-buildx-plugin_0.16.2-1~ubuntu.22.04~jammy_amd64.deb
      curl -o docker-compose-plugin.deb https://download.docker.com/linux/ubuntu/dists/jammy/pool/stable/amd64/docker-compose-plugin_2.29.1-1~ubuntu.22.04~jammy_amd64.deb
    args:
      chdir: /opt/docker

  - name: Docker - Install Packages
    ansible.builtin.shell: |
      dpkg -i ./containerd.io.deb
      dpkg -i ./docker-ce.deb
      dpkg -i ./docker-ce-cli.deb
      dpkg -i ./docker-buildx-plugin.deb
      dpkg -i ./docker-compose-plugin.deb
    args:
      chdir: /opt/docker
      
  - name: Docker - Allow non-sudo access
    ansible.builtin.shell: |
      groupadd docker
      usermod -aG docker "{{ local_user }}"

  - name: Docker Compose - Install
    ansible.builtin.shell: |
        curl -L "https://github.com/docker/compose/releases/download/v2.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose

- name: QEMU
  become: true
  become_user: root
  block:
  - name: QEMU - Install
    ansible.builtin.package:
      name: qemu-system
      state: present

  # OVMF provides UEFI support
  - name: OVMF - Install
    ansible.builtin.package:
      name: ovmf
      state: present
