---
- name: fzf
  block:
  - name: Clone fzf repo
    ansible.builtin.git:
        repo: https://github.com/junegunn/fzf.git
        dest: "$HOME/.fzf"

  - name: Install fzf
    ansible.builtin.command:
      chdir: "$HOME/.fzf"
      cmd: ./install
