---
- name: fzf
  block:
  - name: Clone fzf repo
    ansible.builtin.git:
        repo: https://github.com/junegunn/fzf.git
        dest: "$HOME/.fzf"

  - name: Install fzf
    ansible.builtin.command:
      chdir: "$HOME/.fzf"
      cmd: ./install

- name: bat
  block:
  - name: Bat - Install
    become: true
    become_user: root
    ansible.builtin.package:
      name: bat
      state: present

- name: tailwindcss
  block:
  - name: Tailwind - Ensure directory exists
    ansible.builtin.file:
      path: "$HOME/.tailwindcss"
      state: directory

  - name: Tailwind - Get executable
    ansible.builtin.get_url:
      url: https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64
      dest: "$HOME/.tailwindcss/tailwindcss"

  - name: Tailwind - Update permissions
    ansible.builtin.command:
      cmd: chmod +x tailwindcss
      chdir: "$HOME/.tailwindcss"

- name: AWS CLI
  become: true
  become_user: root
  block:
  - name: AWS CLI - Remove existing installation
    ansible.builtin.file:
      path: /usr/local/aws-cli
      state: absent
  - name: AWS CLI - Unzip
    ansible.builtin.unarchive:
      src: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
      dest: "/tmp"
      remote_src: true
  - name: AWS CLI - Install
    ansible.builtin.command:
      cmd: ./aws/install
      chdir: "/tmp"
  - name: AWS CLI - Remove installer
    ansible.builtin.file:
      path: "/tmp/aws"
      state: absent

- name: AWS CDK
  block:
  - name: AWS CDK - Install
    ansible.builtin.command:
      cmd: npm install -g aws-cdk


- name: dust
  block:
  - name: Dust - Install (du replacement)
    ansible.builtin.command:
      cmd: cargo install du-dust

- name: eza
  block:
  - name: Eza - Install (ls replacement)
    ansible.builtin.command:
      cmd: cargo install eza
        
- name: yazi
  block:
  - name: Yazi - Install (CLI file manager)
    ansible.builtin.command:
      cmd: cargo install --locked yazi-fm yazi-cli

