---
- name: fzf
  block:
  - name: Clone fzf repo
    ansible.builtin.git:
        repo: https://github.com/junegunn/fzf.git
        dest: "$HOME/.fzf"

  - name: Install fzf
    ansible.builtin.command:
      chdir: "$HOME/.fzf"
      cmd: ./install

- name: tailwindcss
  block:
  - name: Tailwind - Ensure directory exists
    ansible.builtin.file:
      path: "$HOME/.tailwindcss"
      state: directory

  - name: Tailwind - Get executable
    ansible.builtin.get_url:
      url: https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64
      dest: "$HOME/.tailwindcss/tailwindcss"

  - name: Tailwind - Update permissions
    ansible.builtin.command:
      cmd: chmod +x tailwindcss
      chdir: "$HOME/.tailwindcss"

