---
- name: fzf
  block:
  - name: Clone fzf repo
    ansible.builtin.git:
        repo: https://github.com/junegunn/fzf.git
        dest: "$HOME/.fzf"

  - name: Install fzf
    ansible.builtin.command:
      chdir: "$HOME/.fzf"
      cmd: ./install

- name: bat
  block:
  - name: Bat - Install
    become: true
    become_user: root
    ansible.builtin.package:
      name: bat
      state: present

- name: tailwindcss
  block:
  - name: Tailwind - Ensure directory exists
    ansible.builtin.file:
      path: "$HOME/.tailwindcss"
      state: directory

  - name: Tailwind - Get executable
    ansible.builtin.get_url:
      url: https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64
      dest: "$HOME/.tailwindcss/tailwindcss"

  - name: Tailwind - Update permissions
    ansible.builtin.command:
      cmd: chmod +x tailwindcss
      chdir: "$HOME/.tailwindcss"

- name: dust
  block:
  - name: Dust - Install (du replacement)
    ansible.builtin.command:
      cmd: cargo install du-dust

- name: eza
  block:
  - name: Eza - Install (ls replacement)
    ansible.builtin.command:
      cmd: cargo install eza
        
