---
# Firefox
- name: Firefox - Ensure policies directory exists
  file:
    path: /etc/firefox/policies
    recurse: true
    state: directory

- name: Firefox - Copy policies
  copy:
    src: policies.json
    dest: /etc/firefox/policies
