---
# Firefox
- name: Firefox - Ensure policies directory exists
  become: true
  become_user: root
  file:
    path: /etc/firefox/policies
    recurse: true
    state: directory

- name: Firefox - Copy policies
  become: true
  become_user: root
  copy:
    src: policies.json
    dest: /etc/firefox/policies

- name: Brave
  become: true
  become_user: root
  block:
  - name: Brave - Get GPG
    ansible.builtin.shell: |
      curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
      echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main"|sudo tee /etc/apt/sources.list.d/brave-browser-release.list

  - name: Brave - Update Packages
    ansible.builtin.shell: |
      apt update

  - name: Brave - Install
    ansible.builtin.shell: |
      apt install brave-browser
