---
- name: ZSH
  block:
  - name: Install zsh
    become: true
    become_user: root
    ansible.builtin.package:
      name: zsh
      state: present

  - name: Set shell to zsh
    become: true
    become_user: root
    shell:
      cmd: "chsh -s $(which zsh) {{ local_user }}"

  - name: Install Oh My Posh
    become: true
    become_user: root
    ansible.builtin.shell: >
        curl -s https://ohmyposh.dev/install.sh | bash -s

- name: Kitty
  block:
  - name: Kitty - Install
    ansible.builtin.shell: >
      curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin 

  - name: Kitty - Symlink kitty to path
    ansible.builtin.command:
      cmd: ln -sf ~/.local/kitty.app/bin/kitty ~/.local/kitty.app/bin/kitten ~/.local/bin/

  - name: Kitty - Copy desktop file to apps folder
    ansible.builtin.command:
      cmd: cp ~/.local/kitty.app/share/applications/kitty.desktop ~/.local/share/applications/

  - name: Kitty - Copy Kitty open file for file manager
    ansible.builtin.command:
      cmd: cp ~/.local/kitty.app/share/applications/kitty-open.desktop ~/.local/share/applications/

  - name: Kitty - Update path for icons
    ansible.builtin.shell: >
      sed -i "s|Icon=kitty|Icon=$HOME/.local/kitty.app/share/icons/hicolor/256x256/apps/kitty.png|g" $HOME/.local/share/applications/kitty*.desktop

  - name: Kitty - Update paths for execs
    ansible.builtin.shell: >
      sed -i "s|Exec=kitty|Exec=$HOME/.local/kitty.app/bin/kitty|g" $HOME/.local/share/applications/kitty*.desktop

  - name: Kitty - Make xdg-terminal-exec
    ansible.builtin.command:
      cmd: echo 'kitty.desktop' > $HOME/.config/xdg-terminals.list
    
- name: tmux
  block:
  - name: tmux - Install
    become: true
    become_user: root
    ansible.builtin.package:
      name: tmux
      state: present

  - name: tmux - Install Tmux Plugin manager
    ansible.builtin.git:
        repo: https://github.com/tmux-plugins/tpm
        dest: $HOME/.tmux/plugins/tpm
